// Barrel file — re-exports from domain modules
export { store } from './core';
export {
  getProject,
  addProject,
  removeProject,
  updateProject,
  getProjectPath,
  getProjectBranchPrefix,
  pickAndAddProject,
  validateProjectPaths,
  relinkProject,
  isProjectMissing,
  projectIsGitRepo,
  PASTEL_HUES,
} from './projects';
export { removeProjectWithTasks } from './project-cleanup';
export {
  loadAgents,
  addAgentToTask,
  closeAgentInTask,
  markAgentExited,
  restartAgent,
  switchAgent,
  addCustomAgent,
  removeCustomAgent,
} from './agents';
export {
  createTask,
  createImportedTask,
  closeTask,
  retryCloseTask,
  mergeTask,
  pushTask,
  updateTaskName,
  updateTaskBranch,
  updateTaskNotes,
  sendPrompt,
  setLastPrompt,
  clearInitialPrompt,
  setInitialPrompt,
  clearPrefillPrompt,
  clearTaskLandingReview,
  setPrefillPrompt,
  reorderTask,
  reorderTaskVisually,
  spawnShellForTask,
  runBookmarkInTask,
  closeShell,
  hasDirectTask,
  collapseTask,
  uncollapseTask,
  getGitHubDropDefaults,
  setNewTaskDropUrl,
  setNewTaskPrefillPrompt,
  setPlanContent,
  setStepsContent,
  setTaskLastInputAt,
  markTaskUserActivity,
  setTaskPromptDraftActive,
  setTaskTerminalInputPending,
  initMCPListeners,
  getCoordinatorCloseWarning,
  setTaskControl,
  markTaskMcpPending,
  markTaskMcpReady,
  setTaskMcpLaunchArgs,
  applyTaskMcpLaunchResult,
  markTaskMcpError,
  retryTaskMcpStartup,
} from './tasks';
export {
  setActiveTask,
  setActiveAgent,
  moveActiveTask,
  jumpToTask,
  toggleNewTaskDialog,
  toggleBlueprintGallery,
  launchBlueprint,
  toggleFanout,
  toggleHandoff,
  toggleEvalArena,
  toggleTelemetry,
  toggleRegistry,
  toggleDiscovery,
  sendSpecToFanout,
} from './navigation';
export {
  allBlueprints,
  saveCustomBlueprint,
  deleteCustomBlueprint,
  duplicateBlueprint,
  setDefaultStack,
} from './blueprints';
export {
  dispatchFanout,
  defaultModules,
  autoSplitModules,
  type FanoutModule,
  type FanoutResult,
} from './fanout';
export { getDesignRefs, addDesignRefs, removeDesignRef } from './design';
export { DEPLOY_TARGETS, handoffTargetsForProject, runHandoff, type ProjectTask } from './handoff';
export {
  runCase,
  aggregateRun,
  emptyCase,
  type EvalCase,
  type EvalRun,
  type EvalCaseResult,
} from './eval';
export {
  getSuite,
  getOrCreateSuite,
  updateSuiteFields,
  commitPromptVersion,
  restorePromptVersion,
  latestVersion,
  latestRun,
  runSuiteEval,
  deleteSuiteRun,
  setHumanVerdict,
  exportDatasetJson,
  buildEmbedEvalsBrief,
  type EvalSuite,
  type EvalRunRecord,
  type PromptVersion,
} from './eval-suites';
export {
  clearTelemetry,
  currentTelemetrySummary,
  PRICING,
  type TelemetryEvent,
  type TelemetrySummary,
  type TelemetryKind,
} from './telemetry';
export {
  getAsset,
  createAsset,
  updateAssetFields,
  deleteAsset,
  duplicateAsset,
  commitAssetVersion,
  restoreAssetVersion,
  latestAssetVersion,
  markAssetUsed,
  captureAsset,
  searchAssets,
  seedRegistryIfNeeded,
  type Asset,
  type AssetVersion,
} from './registry';
export {
  getDiscovery,
  getOrCreateDiscovery,
  updateDiscoveryFields,
  composeDiscoveryBrief,
  refineDiscoveryBrief,
  emptyStep,
  type Discovery,
  type WorkflowStep,
  type StepActor,
} from './discovery';
export {
  registerFocusFn,
  unregisterFocusFn,
  triggerFocus,
  registerAction,
  unregisterAction,
  triggerAction,
  getTaskFocusedPanel,
  setTaskFocusedPanel,
  isPanelFocused,
  isPanelFocusedPrefix,
  focusSidebar,
  unfocusSidebar,
  unfocusPlaceholder,
  navigateRow,
  navigateColumn,
  navigateTask,
  setPendingAction,
  clearPendingAction,
  toggleHelpDialog,
  toggleSettingsDialog,
  sendActivePrompt,
} from './focus';
export type { PanelId, PendingAction, TaskViewportVisibility } from './types';
export { saveState, loadState, loadCustomThemes } from './persistence';
export {
  adjustGlobalScale,
  resetGlobalScale,
  getPanelUserSize,
  setPanelUserSize,
  deletePanelUserSize,
  getTaskViewportVisibility,
  setTaskViewportVisibility,
  toggleSidebar,
  toggleArena,
  toggleFocusMode,
  toggleTaskFocusMode,
  setTaskSplitMode,
  setTerminalFont,
  applyAppearanceMode,
  markCustomThemesReady,
  setAppearanceMode,
  setLightTheme,
  setDarkTheme,
  saveCustomTheme,
  deleteCustomTheme,
  setAutoTrustFolders,
  setShowPlans,
  setShowPromptInput,
  setShowSidebarTips,
  setShowSidebarProgress,
  setProjectsCollapsed,
  setFontSmoothing,
  setDesktopNotificationsEnabled,
  setVerboseLogging,
  setCoordinatorNotificationDelayMs,
  setInactiveColumnOpacity,
  setEditorCommand,
  setDockerImage,
  setDockerAvailable,
  setShareDockerAgentAuth,
  setAskCodeProvider,
  setMinimaxApiKey,
  setWindowState,
  setCoordinatorModeEnabled,
  setDefaultStepsEnabled,
  setDefaultSkipPermissions,
  setDefaultPropagateSkipPermissions,
} from './ui';
export {
  getTaskDotStatus,
  getTaskAttentionState,
  taskNeedsAttention,
  markAgentOutput,
  clearAgentActivity,
  getAgentOutputTail,
  stripAnsi,
  onAgentReady,
  offAgentReady,
  normalizeForComparison,
  normalizeCurrentFrame,
  looksLikeQuestion,
  isTrustQuestionAutoHandled,
  isAgentTrustQuestionAutoHandled,
  isAutoTrustSettling,
  isAgentAskingQuestion,
  isAgentIdle,
  refreshTaskStatus,
  startTaskStatusPolling,
  stopTaskStatusPolling,
  rescheduleTaskStatusPolling,
} from './taskStatus';
export type { TaskAttentionState, TaskDotStatus } from './taskStatus';
export { showNotification, clearNotification } from './notification';
export { startPrChecksSubscription, getPrChecks, type PrChecksState } from './pr-checks';
export { getMergedTasksTodayCount, getMergedLineTotals } from './completion';
export {
  createTerminal,
  closeTerminal,
  updateTerminalName,
  syncTerminalCounter,
} from './terminals';
export { startRemoteAccess, stopRemoteAccess, refreshRemoteStatus } from './remote';
export {
  updateStatus,
  startUpdateSubscription,
  checkForUpdates,
  downloadUpdate,
  installUpdate,
} from './updates';
export {
  resolvedBindings,
  allBindings,
  loadKeybindings,
  selectPreset,
  setUserOverride,
  clearUserOverride,
  resetAllBindings,
  checkConflict,
  dismissMigrationBanner,
} from './keybindings';
export {
  hasAnyCoordinatorTask,
  refreshMCPStatus,
  startMCPStatusPolling,
  stopMCPStatusPolling,
} from './mcpStatus';
